services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-http.rule=Host(`lucasdebeve.eu`) || Host(`www.lucasdebeve.eu`)
      - traefik.http.routers.portfolio-http.entrypoints=websecure
      - traefik.http.routers.portfolio-http.tls.certresolver=myresolver
      - traefik.http.services.portfolio.loadbalancer.server.port=80
      - traefik.http.middlewares.test-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.test-ratelimit.ratelimit.burst=200
      - traefik.http.routers.portfolio-redirect.rule=Host(`www.lucasdebeve.eu`)
      - traefik.http.routers.portfolio-redirect.entrypoints=websecure
      - traefik.http.routers.portfolio-redirect.middlewares=redirect-to-non-www
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\.(.+)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$$1
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
      - glance.name=Portfolio
      - glance.icon=di:vite
      - glance.url=https://www.lucasdebeve.eu
      - glance.description=Portfolio personnel
    networks:
      - frontend
      - app_network

networks:
  frontend:
    external: true
  app_network:
    driver: bridge